Repository Adslot/adslot-ui, pull requests merged in 2019-10, with the labels that each got.

#917 feat: allow toggle switch disabled state
  src/components/adslot-ui/Switch/index.jsx
  src/components/adslot-ui/Switch/style.scss
  www/examples/SwitchExample.jsx
Labels: enhancement, tested

#913 refactor: new color for alert input
  src/components/adslot-ui/AlertInput/index.jsx
  src/components/adslot-ui/AlertInput/index.spec.jsx
  src/components/adslot-ui/AlertInput/styles.scss
  src/components/third-party/Popover/constants.js
  src/components/third-party/Popover/index.spec.jsx
  src/components/third-party/Popover/styles.scss
  www/examples/AlertInputExample.jsx
  www/examples/PopoverExample.jsx
Labels: design reviewed

#935 feat: update new switch color scheme
  src/components/adslot-ui/Switch/style.scss
  src/styles/color.scss
  www/examples/SwitchExample.jsx
Labels: fixupfriday

#934 feat: add disabled support to AlertInput component
  src/components/adslot-ui/AlertInput/index.jsx
  src/components/adslot-ui/AlertInput/index.spec.jsx
  src/components/adslot-ui/AlertInput/styles.scss
  www/examples/AlertInputExample.jsx
Labels: enhancement, fixupfriday
