Repository Adslot/adslot-ui, pull requests merged in 2019-01, with the labels that each got.

#797 Introduce theme to third-party Popover component
  docs/components/Example/styles.scss
  docs/components/Layout/index.jsx
  docs/examples/HelpIconPopoverExample.jsx
  docs/examples/PopoverExample.jsx
  docs/examples/styles.scss
  package-lock.json
  src/components/adslot-ui/AlertInput/index.jsx
  src/components/adslot-ui/HelpIconPopover/index.jsx
  src/components/adslot-ui/HelpIconPopover/index.spec.jsx
  src/components/adslot-ui/HoverDropdownMenu/index.jsx
  src/components/adslot-ui/TextEllipsis/index.jsx
  src/components/third-party/Button/index.jsx
  src/components/third-party/Button/index.spec.jsx
  src/components/third-party/Button/styles.scss
  src/components/third-party/Popover/index.jsx
  src/components/third-party/Popover/index.spec.jsx
  src/components/third-party/index.js
  src/index.js
  src/styles/_bootstrap-custom.scss
  src/styles/bootstrapOverrides/Button.scss
  src/styles/bootstrapOverrides/Popover.scss
  src/styles/border.scss
  src/styles/mixins/popoverTheme.scss
  src/styles/variable.scss
Labels: Need testing🛠, v27 RoadMap :arrow_double_up:

#798 feat: refactor Accordion component
  docs/components/Layout/index.jsx
  docs/components/Navigation/index.jsx
  docs/examples/AccordionExample.jsx
  docs/examples/AccordionPanelExample.jsx
  docs/examples/PanelExample.jsx
  docs/examples/styles.scss
  src/components/adslot-ui/Accordion/AccordionPanel/index.jsx
  src/components/adslot-ui/Accordion/index.jsx
  src/components/adslot-ui/Accordion/index.spec.jsx
  src/components/adslot-ui/Panel/index.jsx
  src/components/adslot-ui/Panel/mocks.js
Labels: Breaking🔨, Need testing🛠

#804 Re-apply the implementation of tab&tabs
  docs/examples/TabExample.jsx
  src/components/adslot-ui/Tab/index.jsx
  src/components/adslot-ui/Tab/index.spec.jsx
  src/components/adslot-ui/Tabs/index.jsx
  src/components/adslot-ui/Tabs/index.spec.jsx
  src/components/adslot-ui/index.js
  src/index.js
Labels: Breaking🔨, v27 RoadMap :arrow_double_up:
